---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: golang-api-cron
  namespace: kubernetes-101
spec:
  # https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#writing-a-cronjob-spec
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: busybox
              image: busybox:1.28
              imagePullPolicy: IfNotPresent
              command:
              - /bin/sh
              - -c
              - date; echo Hello world
          restartPolicy: OnFailure
