apiVersion: v1
kind: Secret
metadata:
  name: secret-config
  namespace: kubernetes-101
  labels:
    app: golang-api
    environment: production
data:
  # need to convert that value to base64
  # cat ../secret/.env | base64
  .env: c2VjcmV0X2tleT1zZWNyZXRfdmFsdWUK
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: kubernetes-101
  labels:
    app: golang-api
    environment: production
data:
  # create configmap to prepare configuration than insert to pod
  config.yaml: |
    config_key=config_value
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: golang-api
  namespace: kubernetes-101
  labels:
    app: golang-api
    environment: production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: golang-api-deployment
  minReplicas: 1
  maxReplicas: 3 # maximum replicas
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 10 # if cpu utilization greater than 50% exec autoscaling
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-api-deployment
  namespace: kubernetes-101
  labels:
    app: golang-api
    environment: production
spec:
  selector:
    matchLabels:
      app: golang-api
      environment: production
  replicas: 1
  template:
    metadata:
      labels:
        app: golang-api
        environment: production
    spec:
      hostname: golang-api
      containers:
        - name: golang-api
          image: adiatma/golang-api
          imagePullPolicy: IfNotPresent
          ports:
            - name: http-golang-api
              containerPort: 8000
          livenessProbe:
            httpGet:
              path: /
              port: http-golang-api
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 1
            successThreshold: 1
          resources:
            requests:
              memory: "54Mi"
              cpu: "250m"
            limits:
              memory: "54Mi"
              cpu: "250m"
          env:
            - name: MESSAGE
              value: hello world
            # get env from secret path
            - name: SECRET_CONFIG
              valueFrom:
                secretKeyRef:
                  name: secret-config
                  key: .env
          # get env from configmap path
          envFrom:
            - configMapRef:
                name: config
          # mapping secret & configmap to pod
          volumeMounts:
            - name: empty-volume
              mountPath: /volume
            - name: secret-config
              readOnly: true
              mountPath: "/secret" # setup secret path
            - name: config
              readOnly: true
              mountPath: "/config" # setup config path
      volumes:
        - name: empty-volume
          emptyDir: {}
        - name: secret-config
          secret:
            secretName: secret-config
        - name: config
          configMap:
            name: config
            items:
            - key: "config.yaml"
              path: "config.yaml"
---
apiVersion: v1
kind: Service
metadata:
  name: golang-api-service
  namespace: kubernetes-101
  labels:
    app: golang-api
    environment: production
spec:
  selector:
    app: golang-api
    environment: production
  ports:
    - protocol: TCP
      port: 80
      targetPort: http-golang-api
  type: ClusterIP # default ClusterIP, options: NodePort, LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: golang-api-ingress
  namespace: kubernetes-101
  labels:
    app: golang-api
    environment: production
spec:
  # defaultBackend:
  #   service: 
  #     name: golang-api-service
  #     port:
  #       port: 80
  ingressClassName: nginx
  # https://kubernetes.io/docs/concepts/services-networking/ingress/#simple-fanout
  rules:
    - host: adiatma.local
      http:
        paths:
         - path: /
           pathType: Prefix
           backend:
            service:
              name: golang-api-service
              port:
                number: 80
