---
apiVersion: v1
kind: Service
metadata:
  name: golang-api-service
  namespace: kubernetes-101
  labels:
    app: golang-api
    environment: production
spec:
  selector:
    app: golang-api
    environment: production
  ports:
    - protocol: TCP
      port: 80
      targetPort: http-golang-api
  type: ClusterIP # default ClusterIP, options: NodePort, LoadBalancer
