---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: kubernetes-101
  labels:
    app: golang-api
    environment: production
data:
  # create configmap to prepare configuration than insert to pod
  config.yaml: |
    config_key=config_value

