---
apiVersion: v1
kind: Secret
metadata:
  name: secret-config
  namespace: kubernetes-101
  labels:
    app: golang-api
    environment: production
data:
  # need to convert that value to base64
  # cat ./secret/.env | base64
  .env: c2VjcmV0X2tleT1zZWNyZXRfdmFsdWUK
